---
name: "✨ Checkov - Terraform"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/checkov.yaml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/checkov.yaml'
  workflow_dispatch: # Allow to manually trigger the pipeline

concurrency: ci-${{ github.ref }}
jobs:
  checkov:
      name: ✨ Checkov
      runs-on: ubuntu-24.04
      steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true
