---
name: "💫 Super-Linter"

on:
  push:

jobs:
  linting:
    name: 💫 super-linter
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          # Full git history is needed
          fetch-depth: 0

      - name: Create reporting dir
        run: mkdir -p super-linter.report

      - name: Run super-linter
        uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # limit to new and updated files
          VALIDATE_ALL_CODEBASE: false