---
name: 🧽 Package cleaner

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch: # Allow to manually trigger the pipeline

permissions:
  contents: read
  packages: write


jobs:
  package-cleaner:
    runs-on: ubuntu-latest

    steps:
      - name: 🧹 Delete old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'agg'
          package-type: 'container'
          min-versions-to-keep: 5
          ignore-versions: 'test.*'
