---
name: 🔬 Tests

on:
  pull_request:
    paths:
      - 'docker/**'
      - 'tests/**'
      - '.github/workflows/tests.yaml'

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: ⚙️ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🪪 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷️ Prepare tag
        id: prep
        run: |
          tag=$(echo ${{ matrix.platform }} | tr '/' '-')
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"

      - name: 🏗️ Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          platforms: ${{ matrix.platform }}
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/ducretje/agg:test-${{ steps.prep.outputs.tag }}

      - name: 🛠️ Set permissions
        run: chmod -R 777 ./tests

      - name: 🧪 Build and test the image
        run: make all IMAGE_NAME=ghcr.io/ducretje/agg:test-${{ steps.prep.outputs.tag }}
        working-directory: ./tests
